### ISSUE TITLE
Support for Story Maps

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#174] opened 2020-01-30 00:12 UTC
This is probably related to #56 .

Some solutions ship a story map as part of the solution and not just as a "Getting to Know" or "How to Configure". See Incident Briefing for an example. 

https://solutions.arcgis.com/emergency-management/help/incident-briefing/

When these are deployed, the original maps in the deployment organization are being referenced, not the new items laid down with the solution.

**Comment by chris-fox** [comment] 2020-01-30 19:58
@shoe913, I think we need to do some more work with Story Maps and we should probably push until after June. Currently in the Pro add-in when we deploy Incident Briefing, it doesn't clone any of the maps or layers, just the story map and it continues to point to items in the try it live. The reason I didn't tackle it is every story map has a different spec.

I think with the new Story Map item type and unified template/spec we can more easily support this moving forward and I am leaning towards never support the old templates because they will be retired eventually.

For now the Getting to Know examples which are just Web Apps with url references will work as handled in issue #56.

**Comment by chris-fox** [comment] 2020-01-30 20:39
@shoe913, this is another example I am guessing where if you edited the template and set the variables they would be swizzled properly and work after deployment.

**Comment by shoe913** [comment] 2020-01-30 22:58
@chris-fox 

I think waiting for the unified template is a good idea for now. 

I've tested the process and we can manually swizzle the story map to the newly deployed items. 

I think this should be the pattern we follow for the few story map solutions we have for the initial release. Since there are so few, it will be easy to document the process or just simply do it on an as needed basis.

**Comment by chris-fox** [comment] 2020-03-02 21:53
Closing as a duplicate of #44. No plans to support old story maps, we will plan to support new StoryMap item type.

**Closed by chris-fox** 2020-03-02 21:53 UTC
Labels: A - bug, C - Behavior
