### ISSUE TITLE
Add ability to swizzle feature services in Pro Project Package item type

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#30] opened 2019-06-06 16:35 UTC
@chris-fox:
>Support swizzling of feature services in Pro Project Package type
> In some cases we will be shipping hosted feature services with Pro Project Packages. We need to be able to clone the feature service and the Pro Project Package and swizzle the service references in the package. A Pro Project is a 7 zip containing a series of json and xml files. We need to be able to extract, modify and recompress so the resulting package references the new feature services in the user's organization.

**Comment by chris-fox** [comment] 2020-01-30 20:40
duplicate of #58

**Closed by chris-fox** 2020-01-30 20:40 UTC
Labels: A - enhancement, B - Moderate, C - Content, D - Investigative Work
